from method import *

assert(swap(30,40)==(40,30))
assert(check(9).lower()==('positive number').lower())
assert(checkDivisor(20,4)==[4,8,12,16,20])
assert(Divide(40,5)==(8,0))
assert(oddNumbers(15)==[1,3,5,7,9,11,13,15])
assert(sumOfDegits(143)==8)
assert(findSmallestDivisor(35)==5)
assert(sumOfSeries(1,3)==123)
assert(reverse(143)==341)
assert(average([1,3,5,7,9])==5)
assert(count(12345)==5)
assert(palindrome(1234321)==True)
assert(ifSubStringFound("Mangalyaan is the second interplanetary mission of India and second mission to Mars","Mangalyaan")==3)
assert(indexSubStringFound("Mangalyaan is the second interplanetary mission of India and second mission to Mars","Mangalyaan")==7)
assert(checkForCharacters("My")==True)
assert(replace("anamika ana")=="$n$mik$ $n$")
assert(countVowels("sadhsdgdfaSADHSDGDFA")==10)
assert(replaceBlankSpace("The Mangalyaan  spacecraft")=="The-Mangalyaan--spacecraft")
assert(findLength("Mangalyaan")==9)
assert(findLargerString("Mangalyaan","The Mangalyaan spacecraft")=="The Mangalyaan spacecraft")
assert(countOfUpperLower("The Mangalyaan")==(2,11))
assert(countCharsDigits("Mangalyaan2")==(10,1))
assert(fullPattern("The Mangalyaan  spacecraft","The Mangalyaan")==True)
assert(cumulative_Sum([1,2,4,5,7])==[1,3,7,12,19])
print(tenRandomNumbers())
print(tenRandomNumbersRange())
print(uniqueRandomNumbers())
print(randomNumbers())
